### ISSUE TITLE
NL file is added to compiled output

### ISSUE THREAD

**Issue by Phoniexk** [skwasjer/IbanNet#123]
With Release [v5.7.1](https://github.com/skwasjer/IbanNet/releases/tag/v5.7.1) you have added "nl" resx files.

On compilation (Debug / Release / Publish) this creates a folder "nl" with "IbanNet.resources.dll"...

I don't need "nl" resources and I also don't need any other resource files. If you add in future more language files, this will mess up compiled output with such files...

Please provide the resources in another way without adding additional files to the output.

**Comment by skwasjer** [comment]
The inclusion of localization only helps further adoption and convenience for the broader audience. Including resource satellite assemblies is common practice for projects that support a large target audience. I do not intend to reinvent the wheel for localization purposes and add extra NuGet packages just for localization purpose alone. IbanNet is not the only project to do so. 

Besides, if you want to exclude satellite assemblies, the .NET SDK has an option to exclude satellite assemblies at 'your' end:
https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#satelliteresourcelanguages
