### ISSUE TITLE
Does Iban work with Entity Framework

### ISSUE THREAD

**Issue by NathanTe** [skwasjer/IbanNet#130]
I read in the documentation that `Iban` class can be used in your domain. I had a few questions about this:

- How does the Iban get stored in DB? as a `string` or as an `reference`?
- Does EF automatically convert it to an instance of Iban? 
- ~~How do I create an `Iban` object from a `string`?~~

If anyone could point me to the right part of the documentation that would be extremely helpful.
Kind regards,
Nathan T.

**Comment by skwasjer** [comment]
You can use the `Iban` type with entity framework in combination with a value converter.

https://learn.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations 

```
public class MyDbContext : DbContext
{
    public MyDbContext(IIbanParser _ibanParser)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<Account>()
            .Property(e => e.AccountNumber)
            .HasConversion(
                iban => iban.ToString(IbanFormat.Electronic),
                ibanStr => _ibanParser.Parse(ibanStr);
    }
}
```

**Comment by NathanTe** [comment]
I wanted to have a `List<Iban>` and that translates to a `List<string>` so then I need to create a wrapper class Iban to store an Iban 😞. So I just made my own Iban class with a string and when needed I parse it to an `Iban` to stringify it.

I will look into replacing the string in my own Iban implementation with the Iban with the value converter.

Thanks for the extra info.
