### ISSUE TITLE
Spaces in a properly formatted IBAN will result in a validation error

### ISSUE THREAD

**Issue by FunnyPaul** [skwasjer/IbanNet#142]
In the 5.3.1 version used in the MVC example (which can be downloaded here), a formatted, valid IBAN is also validated as such.

However, not in the current version 5.9.0, only if the spaces have been removed. Of course, that makes handling more difficult, since I have to replace the spaces in the model, validate them again, then put the formatted string in again, etc.

Is there an option that formatted IBANs that are correct can also be validated without errors?

**Comment by skwasjer** [comment]
This was changed in [v5.7.0](https://github.com/skwasjer/IbanNet/releases/tag/v5.7.0)

Both the data annotations and fluent validation implementations now have a strict parameter (default true), with which you can allow more relaxed validation (whitespace, casing). I will update the wiki when I have some time.

**Comment by FunnyPaul** [comment]
Many thanks for the quick and competent answer. Then it's not a bug :-)

**Comment by skwasjer** [comment]
AspNetCoreExample updated with non-strict in #159.
