### ISSUE TITLE
Add new Supported Countries

### ISSUE THREAD

**Issue by marciooliveiraprimaverabss** [skwasjer/IbanNet#18]
Please add Angola, Mozambique and Cape Verde on Supported Countries.
You can see examples of it on https://en.wikipedia.org/wiki/International_Bank_Account_Number

**Comment by skwasjer** [comment]
v4.0 will have support for multiple providers (IBAN structure sources), but using wiki as a source is out of scope atm. Until then it is parked.

**Comment by skwasjer** [comment]
Will be released in v5
