### ISSUE TITLE
Chinese bank account number (not IBAN, apparently) with only digits fails to validate with IllegalCountryCodeCharactersResult

### ISSUE THREAD

**Issue by petre-c** [skwasjer/IbanNet#187]
**Describe the bug**
A validation for a Chinese bank account number fails with `IllegalCountryCodeCharactersResult`
<img width="978" alt="image" src="https://github.com/skwasjer/IbanNet/assets/15320885/c1def802-5401-4d38-ab60-0c51a67af0fc">
[2700 - sun shine.pdf](https://github.com/skwasjer/IbanNet/files/13500098/2700.-.sun.shine.pdf)

**To Reproduce**
```csharp
new IbanNet.IbanValidator()
		.Validate("79220078814500000410");
```

**Expected behavior**
Please see the invoice [2700 - sun shine.pdf](https://github.com/skwasjer/IbanNet/files/13500098/2700.-.sun.shine.pdf)

**IbanNet library/version**
- IbanNet 5.12.0

**.NET runtime**
- .NET 7.0

**Operating system**
 - Windows 11 & Ubuntu Linux (latest version 🙂)

**Comment by petre-c** [comment]
According to ChatGPT, China does not use IBAN codes in their bank account numbers.

Can you support validating Chinese bank account numbers?

**Comment by NiKiZe** [comment]
A IBAN number always has a countrycode. If you want to validate national bank accounts you need some other library.

**Comment by skwasjer** [comment]
@petre-c This library is specifically designed to validate IBAN's (as @NiKiZe also points out) according to the [ISO13616 standard](https://www.iso13616.org/). So I am afraid we cannot help you out until maybe one day when China decides to adopt IBAN.
