### ISSUE TITLE
Iceland is listed as Non-Sepa country

### ISSUE THREAD

**Issue by MT-private** [skwasjer/IbanNet#194]
The default country registry lists Iceland as non Sepa-country.
Possibly because of the Swifts txt-file. In the Swifts-PDF it is correctly declared as Sepa-member, which imho is correct.

**Comment by skwasjer** [comment]
Open for contrib. Inspiration can be found here:

https://github.com/skwasjer/IbanNet/tree/main/src/IbanNet.CodeGen/Swift/Patches
