### ISSUE TITLE
Generate Iban

### ISSUE THREAD

**Issue by ekjuanrejon** [skwasjer/IbanNet#21]
Is it possible to generate an iban?

**Comment by skwasjer** [comment]
Not at the moment. For testing purposes, the best that is possible atm, is using the `IbanCountry.Iban.Example` property.

```
IbanRegistry.Default.TryGetValue("NL", out IbanCountry country);
Debug.WriteLine(country.Iban.Example);
```

I will probably add something like this at some point, but can't say when.
