### ISSUE TITLE
The IBAN parser evaluates the bank code incorrectly for Finland (FI)

### ISSUE THREAD

**Issue by Vaclav-Rozsypal** [skwasjer/IbanNet#224]
**Describe the bug**
The IBAN parser evaluates the bank code incorrectly for Finland (FI)

**To Reproduce**
IBAN: FI4017453000182859 result bank code is 174
IBAN: FI2840554920113105 result bank code is 405

**Expected behavior**
IBAN: FI4017453000182859 result bank code is 174530
IBAN: FI2840554920113105 result bank code is 405549

**IbanNet library/version**
IbanNet 5.16.0

**.NET runtime**
.NET Framework 4.6.2

**Operating system**
Windows 10

**Additional context**

**Comment by skwasjer** [comment]
So this is yet another case of the official registry being wrong (for more than 4yrs no less), kinda depressing... 🙈 
I'm just loading the information from their spec but have run into issues such as this countless of times.

Anyway, should be an easy fix via a record patch during code gen.


![image](https://github.com/user-attachments/assets/665031eb-613e-4bbe-9cfb-50cff47594b9)
