### ISSUE TITLE
AttemptedValue does not match actual value used in validation

### ISSUE THREAD

**Issue by Hoffs** [skwasjer/IbanNet#23]
Basically when validation is attempted it "normalizes" the input and uses that in validation context. But then it creates validation result and uppercases it there, thus `AttemptedValue` is not equals to `normalizedIban`.
Reference: https://github.com/skwasjer/IbanNet/blob/39f9b9adf2b5158903d1a738ee4f4f6cc2372a85/src/IbanNet/IbanValidator.cs#L84-L91

**Comment by skwasjer** [comment]
True. The intent of attempted value was to produce a consistent form for the IBAN (upper case), but is not accurate as you describe and should already be covered by the `IbanParser` and `Iban` type which also do this. It warrants a minor version bump though.
