### ISSUE TITLE
Lowercased country code fails with InvalidStructureResult

### ISSUE THREAD

**Issue by Hoffs** [skwasjer/IbanNet#24]
I have been looking at this for a while and can't find concrete information which way it should work. Right now I can see that the validation in `StructureValidator` tries to match first symbols with expected country code. As I see, because country code is lowercased it will not be equals to expected country code which is always uppercased:

https://github.com/skwasjer/IbanNet/blob/39f9b9adf2b5158903d1a738ee4f4f6cc2372a85/src/IbanNet/Validation/StructureValidator.cs#L18

But in other places, like Mod97 validation or finding iban country it uses upper cased ones, which makes it pass:
https://github.com/skwasjer/IbanNet/blob/39f9b9adf2b5158903d1a738ee4f4f6cc2372a85/src/IbanNet/Validation/Rules/IsValidCountryCodeRule.cs#L43-L52
https://github.com/skwasjer/IbanNet/blob/39f9b9adf2b5158903d1a738ee4f4f6cc2372a85/src/IbanNet/CheckDigits/Calculators/Mod97CheckDigitsCalculator.cs#L47-L50

So I wonder, is this valid and expected behavior?

**Comment by skwasjer** [comment]
The check digits calculation is correctly ignoring case, as is the country code rule. I think this is a remnant of older implementation where IbanNet was built around Swift registry specifically, but was refactored to support multiple providers. However, this specific country code check should actually be made a 'test' and injected as a `StructureSegmentTest`.
