### ISSUE TITLE
Morocco bank accounts validation

### ISSUE THREAD

**Issue by nabilelmahiri** [skwasjer/IbanNet#244]
Hello, i would like to use this package for Morocco iban(RIB) validation, is there any plan to integrate  this country in the near future ? 
Thank you very much

**Comment by skwasjer** [comment]
Morocco is not enabled by default, as it is not part of the official SWIFT registry but it is still supported:
https://github.com/skwasjer/IbanNet/blob/main/SupportedCountries.md

You can enable support by registering the alternative `WikipediaRegistryProvider` in DI or by passing it in via options:
https://github.com/skwasjer/IbanNet/wiki/Options#other-registry-providers

As far as Clé Rib support, IbanNet is specifically designed around IBAN, so the short answer is no as it is beyond the scope. I worked on an extension library for validating BBAN. It provides Clé Rib validation for France and its territories though, not for Morocco:
https://github.com/skwasjer/IbanNet/wiki/IbanNet.Extensions.Bban

Not sure if this is was you were looking for, my knowledge on Rib is limited.

**Comment by skwasjer** [comment]
Assuming the answer was satisfactory, so closing.
