### ISSUE TITLE
Migration to latest version of FluentValidation (10.0.0)

### ISSUE THREAD

**Issue by TerraVenil** [skwasjer/IbanNet#30]
Do you have any plans related to migration of Iban.FluentValidaiton to the latest version of FluentValudation (10.0.0)?

**Comment by skwasjer** [comment]
Absolutely, that said, it is still out fresh and already received a number of iterations. It is unfortunate `PropertyValidator` is removed (it says deprecated, but no backward functionality provided). 

The downside of the current repo setup is I cannot major bump a single package individually, they are all linked so a major bump affects all packages. Will have a look if I can change this setup as well.

**Comment by TerraVenil** [comment]
Any chance to look into it? Do you need help?

**Comment by skwasjer** [comment]
You can propose the change in a PR if you want. But a merge will have to wait until a v5 at this point.

I took this as a signal to give some priority first to add some new functionality that causes some breaking changes on its own and I want to release as part of v4.x.

And then remove a lot of obsolete stuff in a prerelease of v5, this change can go along with it.

**Comment by skwasjer** [comment]
Will be released with v5
