### ISSUE TITLE
How to have translated validation error messages?

### ISSUE THREAD

**Issue by jeroenheijmans** [skwasjer/IbanNet#94]
I see the error messages come from [a `.resx` file](https://github.com/skwasjer/IbanNet/blob/main/src/IbanNet/Resources.resx). When using the library in my own project, is there a (recommended) way to add error messages translated in my own language? For example by adding a `nl-NL` resx file as an embedded resource or something similar?

I checked [the wiki](https://github.com/skwasjer/IbanNet/wiki) but found mostly information on how to _use_ this library.

Thanks a bunch for a nice bit of open source, either way! <3

**Comment by skwasjer** [comment]
Indeed a `<Filename>.<locale>.resx` would need to be added to this repo and included as part of the build. If you are up for it, be my guest. I do think there may be some areas where strings possibly still need to be extracted into the resources files (some exceptions are very niche/edge case that I did not bother to add to resx file).

**Comment by skwasjer** [comment]
Also, if you just use DataAnnotations or FluentValidation, you can actually use your own generic messages:

### DataAnnotations 
```
[Iban(ErrorMessageResourceName = "MyResourceName", ErrorMessageResourceType = typeof(Resources))]
public string BankAccount { get; set; }
```

### FluentValidation
```
RuleFor(x => x.BankAccount).Iban(ibanValidator).WithMessage("MyMessage")
```

**Comment by jeroenheijmans** [comment]
Ooh nice, the latter comment's option I'll investigate, seems to be just what I need.

I could add the nl-NL resources to the library itself in a PR as well. And you'd be most welcome to ping me for translations of new/changed strings. But... I can also imagine as an OSS maintainer you'd prefer _not_ to have the burden of (potentially stale) extra locales.

Let me know if you want nl-NL translation contributions from my end, or prefer to leave it as is.

PS. If we leave it as is I'll check your other suggestion and instead write up some docs for the repository or wiki for others to find.

**Comment by skwasjer** [comment]
Any contrib is appreciated, both to the wiki and code. Localization is fine, yes it can be cumbersome to maintain but I don't expect many textual changes. Plus, I can help with Dutch ;P
